### ISSUE TITLE
Allow custom attributes on a Field

### ISSUE THREAD

**Issue by akand074** [graphql-js/graphene#10]
Currently, any field/type only accepts fixed attributes:

```
args: fieldArgs,
type: _type,
description: config.description,
deprecationReason: config.deprecationReason,
resolve: config.resolver
```

A number of graphql tools depend on attaching attributes to GraphQL types. For example, I may want to use a package like https://github.com/ivome/graphql-query-complexity#customizing-complexity-calculation

If I want to specify complexity on a field to be used for validation, it requires something like:
```
const Post = new GraphQLObjectType({
  name: 'Post',
  fields: () => ({
    title: { type: GraphQLString },
    text: { type: GraphQLString, complexity: 5 },
  }),
});
```
Currently if I add `complexity` to a field like:
```
@Field(String, { args: {}, complexity: 5}) text
```

The complexity attribute would just be ignored and not attached to the GraphQL type.

For any middleware built myself, I can probably use `reflect-metadata` like Graphene is using for their decorators and read the metadata on a target in the middleware _I think_, which is pretty cool but not being able to use other packages is pretty limiting.

**Comment by syrusakbary** [comment]
That's a great suggestion. I'm working on a fix now :)

**Comment by syrusakbary** [comment]
This is now supported in [v0.5.2](https://github.com/graphql-js/graphene/releases/tag/v0.5.2) available in npm.
