### ISSUE TITLE
Is this implementation supposed to work?

### ISSUE THREAD

**Issue by agonbina** [graphql-js/graphene#2]
Hi, judging by the docs it sounds like this(rough) implementation is supposed to work? 
I have tried to implement a couple of things but I am failing to get it to work. Even the examples provided in the repo don't seem to be working.

Could you please report if this library is not at a state where all mentioned features are working?

Just for the record here is what I've tried:

```typescript
class User extends graphene.ObjectType {
  static fields = {
    id: new graphene.ID({ required: true }),
    name: new graphene.String({ required: true }),
    followers: new graphene.Int({ required: true })
  }
  static interfaces = []
}

class Filter extends graphene.ObjectType {
  static fields = {
    id: new graphene.ID({ required: true })
  }
}

class Query extends graphene.ObjectType {
  static fields = {
    User: new graphene.Field(User, {
      required: true,
      args: {
        filter: new graphene.Argument(Filter)
      },
      resolver: (root: any, { filter }: any) => {}
    }),
    me: new graphene.Field(User)
  }
  static interfaces = []
}
```
I then initialise the `Schema` using this `Query` and the main issue is that the `args` for the User query are not passed correctly thus the final schema output ends up like:

```graphql
type Query {
  User: User!
  me: User
}

type User {
  id: ID!
  name: String!
  followers: Int!
}
```
Thanks.

p.s. Extending `graphene.Enum` does not seem to even compile when using TS. I get `Class constructor Enum cannot be invoked without 'new'` when copying the `Episode` enum from the starwars example and trying to use it exactly as it is in the example(ie as a query argument)

**Comment by syrusakbary** [comment]
Hi @agonbina,

This package is still in experimental stage, so there are few things that still need some polish.
The main reason the argument is not showing in the schema repr is because a `ObjectType` (`Filter`) is being used as an `Argument`.

You can solve this by doing:
```js
class User extends graphene.ObjectType {
  static fields = {
    id: new graphene.ID({ required: true }),
    name: new graphene.String({ required: true }),
    followers: new graphene.Int({ required: true })
  }
  static interfaces = []
}

class Filter extends graphene.InputObjectType {
  static fields = {
    id: new graphene.ID({ required: true })
  }
}

class Query extends graphene.ObjectType {
  static fields = {
    User: new graphene.Field(User, {
      required: true,
      args: {
        filter: new Filter()
      },
      resolver: (root: any, { filter }: any) => {}
    }),
    me: new graphene.Field(User)
  }
  static interfaces = []
}
```

Let me know if this solves your issues.

Also, I would love to review the issue you're having when using `graphene.Enum`.
Here is an example of `graphene.Enum` in Typescript, in case is useful: https://github.com/graphql-js/graphene/blob/master/examples/starwars-ts/schema.ts#L13-L29

**Comment by agonbina** [comment]
@syrusakbary extending from `InputObjectType` does not fix the issue. The arg is still missing from the query.

Re: enum, it seems like you have a tsconfig configuration which behaves(compiles) TS in a different way to what I have so I was getting TS errors.

You should also look into generating a type declaration file before publishing the build to npm. I have managed to do this locally but there is still a lot of warnings(and errors) because of the way tsconfig is configured for the library.
